# Generated by Django 3.0 on 2020-07-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200705_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
